version: '3.8'

services:
  eureka:
    build: ./eureka
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gateway:
    build: ./gateway
    ports:
      - "8000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka

  authentication-service:
    build: ./authentication-service
    ports:
      - "8001:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - auth-db
      - eureka

  email-service:
    build: ./email-service
    ports:
      - "8002:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - kafka
      - eureka

  ventas-back:
    build: ./ventas-back
    ports:
      - "8004:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - ventas-db
      - kafka
      - eureka

  recommendation-service:
    build: ./recommendation-service
    ports:
      - "8003:8000"
    environment:
      - DB_HOST=recommendation-db
      - DB_PORT=5432
      - DB_USER=recouser
      - DB_PASS=recopass
      - DB_NAME=recodb
    depends_on:
      - recommendation-db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"

  ventas-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ventasuser
      POSTGRES_PASSWORD: ventaspass
      POSTGRES_DB: ventasdb
    ports:
      - "5435:5432"

  recommendation-db:
    image: postgres:15
    environment:
      POSTGRES_USER: recouser
      POSTGRES_PASSWORD: recopass
      POSTGRES_DB: recodb
    ports:
      - "5434:5432"
