spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://auth-db:5432/authdb
    driver-class-name: org.postgresql.Driver
    username: authuser
    password: authpass
    hikari:
      maximum-pool-size: 10

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
