spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    driver-class-name: org.postgresql.Driver
    username: authuser
    password: authpass
    hikari:
      maximum-pool-size: 10

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/